### ISSUE TITLE
Twitter-integration: update on working status

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad-admin-documentation#263]
To my knowledge the Twitter-integration is not working and the future of the API uncertain. Maybe we should add a note to the part of documentation and keep that updated?

**Comment by ralf401** [comment]
@YetAnotherGerrit 
We can add a note to our documentation. However, the question is _what_ we should write. For me it looks like it is unclear if the API works or not. Is anybody able to provide feedback on this or did you test it yourself? 

Due to the doubtful future of Twitter, perhaps @KoJie or @martini can give some hints about the future plans?

**Comment by dominikklein** [comment]
I think @fliebe92  can give some information here about a first hint and the current API state.

**Comment by fliebe92** [comment]
We are going to talk about our Twitter integration in the next week. After this, it should be clear what we can write into our documentation etc.

Current state is:
- Our own registered apps for usage of Twitter API are suspended
- New tiers for API usage are active (free, basic, pro) - none of them provides the same API as before
  - Enterprise tier provides search endpoints + webhooks (for mentions etc.), but it is very expensive (starting at 42k $ per month) and you need to apply for it via a Google Doc form...

Stay tuned 🤷
