### ISSUE TITLE
Setting `embed_images` deprecated

### ISSUE THREAD

**Issue by mgruner** [zammad/zammad-admin-documentation#416]
```
/opt/homebrew/lib/python3.11/site-packages/docutils/writers/__init__.py:80: FutureWarning: The configuration setting "embed_images" will be removed in Docutils 2.0. Use "image_loading: link".              
  self.translate()
```

**Comment by mgruner** [comment]
@dvuckovic is this something we can / should check?

**Comment by dvuckovic** [comment]
I think we are stuck with this for now: `docutils` is used internally by `Sphinx`, and we are still on `Sphinx-4.5.0` since it's a pre-requisite for the theme we are relying on (`sphinx-rtd-theme 1.2.2`).

If you remember, I tried unpining these dependencies some time ago, but this didn't go very well: there were notable differences in the builds and not an obvious upgrade path that we could follow in order to address all of them.

Best would be to leave it like it is for now and ignore this deprecation warning. I doubt we would be able to use newer versions of `docutils` too with this toolchain, so perhaps it's a non-issue.

Hopefully we can move to a more modern toolchain soon.

**Comment by mgruner** [comment]
Thanks!
