### ISSUE TITLE
Localization of triggers and schedulers

### ISSUE THREAD

**Issue by fliebe92** [zammad/zammad-admin-documentation#506]
In https://github.com/zammad/zammad/commit/c7afe512ad8c3667716161299b88cf6635dd6972, we introduced the localization of triggers and schedulers.

We need to update the available screenshots for triggers and schedulers and maybe a short explanation what's possible now.

Feel free to get in touch with @tschaefer and me for further information.

**Comment by dvuckovic** [comment]
@ralf401 Slight adjustment to the localization/timezone dropdowns in triggers and schedulers: they are now "hidden" by default, but the admin can easily expand it in order to customize them. Also, the context is now explained a bit better within the confines of the UI, hopefully not degrading the UX too much.

![Mar-25-2024 16-22-36](https://github.com/zammad/zammad-admin-documentation/assets/6049445/1c7e8867-e8e7-4e45-b11d-f82b23a51b8c)
