### ISSUE TITLE
Big organizations are no problem?! Only if one user has many?

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad-admin-documentation#566]
This might be obsolete information:

```
BIG organizations can cause performance issues. Especially organizations with many members can cause a fairly high system load if their members run many updates, for example ticket creations or frequent communication.
```

We have some limitations to organizations counts at one user. But there is no general issue with the organization count.

https://github.com/zammad/zammad-admin-documentation/blob/main/manage/organizations/index.rst
```[tasklist]
### Tasks
- [ ] Add a new testsystem and check organizations with 10k+ members if there are still issues with it
```

**Comment by MrGeneration** [comment]
So Zammad is no longer updating all organization members and the tickets they're referenced to in any way if an agent receives a new ticket or updates one? Because that's what this warning is about: It will cloak up your delayed jobs and ultimatively end in performance issues if you're a busy company with many agents in one organization.

**Comment by rolfschmidt** [comment]
I only remember the elasticsearch issue related to jobs which was fixed. But maybe you are right and we should do some tests again before touching this.

**Comment by rolfschmidt** [comment]
I will close this for now.
