### ISSUE TITLE
Add LDAP 2-way sync integration

### ISSUE THREAD

**Issue by snolahc** [zammad/zammad-admin-documentation#96]
Hello,

My team and my customers are stored in an OpenLDAP directory. I'm setting up a ticketing/helpdesk system, and Zammad seems perfect for what we do.
But, the synchronization between the central directory and Zammad is one-way only, and your documentation explicitly says that changes made in Zammad will be overwritten by LDAP on next sync.
I cannot have two entry points for filling customers info, therefore i cannot choose your solution for this specific reason.
My question is : do you intend to finish the work on LDAP integration or is it not at all in the roadmap and i should look for other solutions ?
Thanks a lot,
snolahc

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
